include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-modeminfo
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_LICENSE:=GPLv3
PKG_MAINTAINER:=Modified

LUCI_TITLE:=Information dashboard for 3G/LTE dongle
LUCI_TYPE:=applications
LUCI_DEPENDS:=+modeminfo
LUCI_PKGARCH:=all

include $(TOPDIR)/luci.mk
