#!/bin/sh /etc/rc.common
START=98
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /opt/simadmin/simadmin serve
    procd_set_param env SIMADMIN_ENABLE_NETWORKMANAGER=0
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
