config settings 'main'
    option enable_email '0'
    option smtp_server 'smtp.gmail.com'
    option smtp_port '465'
    option smtp_user 'your_email@gmail.com'
    option smtp_pass 'your_app_password'
    option email_to 'destination@example.com'
    option email_from 'router@example.com'