# Copyright 2017-2026 Dirk Brenken (dev@brenken.org)
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-travelmate-mod
PKG_VERSION:=2.4.0
PKG_RELEASE:=3
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Modified

LUCI_TITLE:=LuCI support for Travelmate (Modified)
LUCI_DEPENDS:=+luci-base +luci-lib-uqr +travelmate
LUCI_PKGARCH:=all

include $(TOPDIR)/luci.mk


# call BuildPackage - OpenWrt buildroot signature
