#!/bin/sh
#
# Copyright (c) 2020-2022 HandsomeMod Project
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

# bind usb0 to br-lan 
uci del_list network.@device[0].ports='usb0'
uci add_list network.@device[0].ports='usb0'

# set firewall mtu_fx
#uci set firewall.@zone[1].mtu_fix='0'

# create modem interface
uci set network.modem=interface
uci set network.modem.proto='modemmanager'
uci set network.modem.device='qcom-soc'
uci set network.modem.auth='none'
uci set network.modem.iptype='ipv4v6'
uci set network.modem.autoconnect='1'
uci set network.modem.auto='1'
uci del_list firewall.@zone[1].network='modem'
uci add_list firewall.@zone[1].network='modem'
uci del_list firewall.@zone[1].device='wwan0'
uci add_list firewall.@zone[1].device='wwan0'
uci commit

# set dns
uci add_list dhcp.@dnsmasq[0].server='1.1.1.1'
uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
uci add_list dhcp.@dnsmasq[0].server='8.8.4.4'
uci add_list dhcp.@dnsmasq[0].server='223.5.5.5'
uci commit dhcp

# restart network
/etc/init.d/network restart
sleep 5
/etc/init.d/dnsmasq restart

# HACK : restart network to find modem after reboot
# echo -e '/etc/init.d/gc restart \n ' > /etc/rc.local
# echo 'sleep 25 && /etc/init.d/network restart' > /etc/rc.local

apk del openstick-tweaks
