#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only

rootpart=$(findmnt -n -o SOURCE /)
rootfstype=$(findmnt -n -o FSTYPE /)

# rootfs-resizer only supports ext4.
# For SquashFS/OverlayFS, do nothing.
if [ "$rootfstype" != "ext4" ]; then
	echo "rootfs-resizer: root filesystem is $rootfstype, skip resize"
	rm -f /etc/uci-defaults/00_rootfs_resizer
	exit 0
fi

mount -o ro,remount /
tune2fs -O^resize_inode ${rootpart}
fsck.ext4 -yDf ${rootpart} > /dev/null
mount -o rw,remount /
resize2fs ${rootpart} > /dev/null

apk del rootfs-resizer
reboot