#
# Copyright (C) 2020-2022 HandsomeMod Project
#
# This is free software, licensed under the GNU General Public License v3.
#
#



include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-modeminfo
PKG_VERSION:=1.0
PKG_RELEASE:=1
LUCI_TITLE:=Modem information for LuCI
LUCI_DEPENDS:=+libubox
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
