include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-modeminfo
PKG_VERSION:=1.0
PKG_RELEASE:=1
LUCI_TITLE:=Modem information for LuCI
LUCI_DEPENDS:=+libubox
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
